// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Infrastructure;

#nullable disable

namespace PersonalFinance.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714234227_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PersonalFinance.Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Gastos del hogar",
                            Titulo = "Hogar"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Ingresos por sueldo",
                            Titulo = "Sueldo"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Ahorros e inversiones",
                            Titulo = "Ahorro"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Entretenimiento y tiempo libre",
                            Titulo = "Ocio"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaMensaje")
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoError")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Procesado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("PersonalFinance.Domain.Moneda", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsBase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TipoCambio")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Monedas");

                    b.HasData(
                        new
                        {
                            Codigo = "ARS",
                            EsBase = true,
                            TipoCambio = 1m
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MensajeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TipoCambioHistorico")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MensajeId");

                    b.HasIndex("MonedaCodigo");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("PersonalFinance.Domain.Movimiento", b =>
                {
                    b.HasOne("PersonalFinance.Domain.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Domain.Mensaje", "Mensaje")
                        .WithMany()
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Domain.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Mensaje");

                    b.Navigation("Moneda");
                });
#pragma warning restore 612, 618
        }
    }
}
