// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Bot.Data;

#nullable disable

namespace PersonalFinance.Bot.Migrations
{
    [DbContext(typeof(PersonalFinanceContext))]
    partial class PersonalFinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "ingresos por sueldo o salario",
                            Titulo = "Sueldo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "gastos del hogar",
                            Titulo = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "comida y supermercado",
                            Titulo = "Comida"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "transporte y combustible",
                            Titulo = "Transporte"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "entretenimiento y salidas",
                            Titulo = "Ocio"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "movimientos sin categoría específica",
                            Titulo = "Otros"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaRecibido")
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Procesado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MensajeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MensajeId")
                        .IsUnique();

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Movimiento", b =>
                {
                    b.HasOne("PersonalFinance.Bot.Domain.Categoria", "Categoria")
                        .WithMany("Movimientos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Bot.Domain.Mensaje", "Mensaje")
                        .WithOne("Movimiento")
                        .HasForeignKey("PersonalFinance.Bot.Domain.Movimiento", "MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Categoria", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("PersonalFinance.Bot.Domain.Mensaje", b =>
                {
                    b.Navigation("Movimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
