// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Infrastructure.Persistencia;

#nullable disable

namespace PersonalFinance.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(PersonalFinanceDbContext))]
    partial class PersonalFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PersonalFinance.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("FechaRecepcionUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("IdentificadorCanal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntentosClasificacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoError")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Procesado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TieneError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorCanal")
                        .IsUnique();

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entidades.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsBase")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TipoDeCambio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Monedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Codigo = "ARS",
                            EsBase = true
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entidades.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MensajeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonedaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Monto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TipoDeCambioHistorico")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("MonedaId", "Fecha");

                    b.ToTable("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
